export const recommendedFonts = [
  "Impact",
  "Comic Sans MS",
  "Alfa Slab One",
  "Anton",
  "Bangers",
  "Bebas Neue",
  "Black Ops One",
  "Chewy",
  "Creepster",
  "Fredoka One",
  "Gloria Hallelujah",
  "Lobster",
  "Luckiest Guy",
  "Oswald",
  "Press Start 2P",
  "Rubik",
  "Shrikhand",
  "Staatliches",
]

export const otherFonts = [
  "Arial",
  "Helvetica",
  "Times New Roman",
  "Verdana",
  "Tahoma",
  "Trebuchet MS",
  "Georgia",
  "Courier New",
  "Lucida Sans",
  "Palatino Linotype",
  "Garamond",
  "Bookman",
  "Candara",
  "Comic Neue",
  "Montserrat",
  "ABeeZee",
  "Abel",
  "Abril Fatface",
  "Acme",
  "Alata",
  "Albert Sans",
  "Alegreya",
  "Alice",
  "Almarai",
  "Amatic SC",
  "Amiri",
  "Antic Slab",
  "Architects Daughter",
  "Archivo",
  "Arimo",
  "Arsenal",
  "Arvo",
  "Asap",
  "Asap Condensed",
  "Assistant",
  "Barlow",
  "Be Vietnam Pro",
  "Bitter",
  "Bodoni Moda",
  "Bree Serif",
  "Bungee",
  "Cabin",
  "Cairo",
  "Cantarell",
  "Cardo",
  "Catamaran",
  "Caveat",
  "Chakra Petch",
  "Changa",
  "Chivo",
  "Cinzel",
  "Comfortaa",
  "Commissioner",
  "Concert One",
  "Cookie",
  "Cormorant",
  "Courgette",
  "Crete Round",
  "Crimson Pro",
  "Cuprum",
  "DM Sans",
  "Dancing Script",
  "Didact Gothic",
  "Domine",
  "Dosis",
  "EB Garamond",
  "Eczar",
  "El Messiri",
  "Electrolize",
  "Encode Sans",
  "Exo",
  "Figtree",
  "Fira Sans",
  "Fjalla One",
  "Francois One",
  "Frank Ruhl Libre",
  "Fraunces",
  "Gelasio",
  "Gothic A1",
  "Great Vibes",
  "Gruppo",
  "Heebo",
  "Hind",
  "IBM Plex Sans",
  "Inconsolata",
  "Indie Flower",
  "Inter",
  "Josefin Sans",
  "Jost",
  "Kalam",
  "Kanit",
  "Karla",
  "Kaushan Script",
  "Khand",
  "Lato",
  "League Spartan",
  "Lexend",
  "Libre Baskerville",
  "Lilita One",
  "Lora",
  "M PLUS 1p",
  "M PLUS Rounded 1c",
  "Macondo",
  "Manrope",
  "Marcellus",
  "Martel",
  "Mate",
  "Maven Pro",
  "Merienda",
  "Merriweather",
  "Mukta",
  "Mulish",
  "Nanum Gothic",
  "Nanum Gothic Coding",
  "Nanum Myeongjo",
  "Neuton",
  "Noticia Text",
  "Noto Sans",
  "Old Standard TT",
  "Oleo Script",
  "Open Sans",
  "Orbitron",
  "Outfit",
  "Overpass",
  "Oxygen",
  "PT Sans",
  "Pacifico",
  "Passion One",
  "Pathway Gothic One",
  "Patua One",
  "Paytone One",
  "Permanent Marker",
  "Philosopher",
  "Play",
  "Playfair Display",
  "Plus Jakarta Sans",
  "Poppins",
  "Prata",
  "Prompt",
  "Public Sans",
  "Quattrocento",
  "Quattrocento Sans",
  "Questrial",
  "Quicksand",
  "Rajdhani",
  "Raleway",
  "Readex Pro",
  "Red Hat Display",
  "Righteous",
  "Roboto",
  "Rokkitt",
  "Rowdies",
  "Russo One",
  "Sacramento",
  "Saira",
  "Saira Condensed",
  "Sarabun",
  "Satisfy",
  "Sawarabi Gothic",
  "Sawarabi Mincho",
  "Sen",
  "Shadows Into Light",
  "Signika",
  "Signika Negative",
  "Silkscreen",
  "Six Caps",
  "Slabo 27px",
  "Sora",
  "Source Sans 3",
  "Space Grotesk",
  "Space Mono",
  "Special Elite",
  "Spectral",
  "Tajawal",
  "Tangerine",
  "Teko",
  "Tinos",
  "Titan One",
  "Titillium Web",
  "Ubuntu",
  "Unbounded",
  "Unna",
  "Urbanist",
  "Varela Round",
  "Vollkorn",
  "Work Sans",
  "Yanone Kaffeesatz",
  "Yantramanav",
  "Yellowtail",
  "Yeseva One",
  "Zen Kaku Gothic New",
  "Zeyada",
  "Zilla Slab",
]
